### El API está levantada
http://localhost:3000/

### Documentación del API
http://localhost:3000/api-docs

#########################
### PUBLICO - LOGIN ###
#########################
### USUARIO --> POST (login de usuario)
POST http://localhost:3000/api/public/login
Content-Type: application/json

{
    "email": "achacon@gmail.com",
    "password": "123456"
}

#########################
### PUBLICO - ALUMNOS ###
#########################
### ALUMNOS --> POST (registro de un alumno)
POST http://localhost:3000/api/public/alumnos/register
Content-Type: application/json

{
    "nombreCompleto": "Almudena del Álamo Santamaría",
    "userName": "aalamo",
    "email": "aalamo@gmail.com",
    "password": "123456"
}

############################
### PUBLICO - PROFESORES ###
############################
### PROFESORES --> POST (registro de un profesor)
POST http://localhost:3000/api/public/profesores/register
Content-Type: application/json

{
    "nombreCompleto": "Isaac Albéniz Taylor",
    "userName": "ialbeniz",
    "email": "ialbeniz@gmail.com",
    "password": "123456",
    "descripcion": "Análisis numérico a tu alcance", 
    "precioHora": 22, 
    "experiencia": 10,
    "latitud": 51.0754421,
    "longitud": 12.4878035, 
    "telefono": "555555555",
    "ramaId": 4
}

#######################
### PUBLICO - RAMAS ###
#######################
### RAMAS --> GET (recuperamos todas)
http://localhost:3000/api/public/ramas/

### RAMAS --> GET (paginadas)
http://localhost:3000/api/public/ramas/?page=2&limit=2

#########################
### PRIVADO - ALUMNOS ###
#########################
### ALUMNOS --> PUT (actualización de los datos de un alumno que no sean la password - solo lo puede hacer él mismo -)
PUT http://localhost:3000/api/private/alumnos/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDAsInJvbGUiOiJhbHVtbm8iLCJleHBpcmF0aW9uX2RhdGUiOjE2Njg1ODcwMTYsImlhdCI6MTY2ODU2OTAxNn0.KNke479x1xC-v4GaIHf64f2o7FgAaOqclJZw_IEByDo

{
    "nombreCompleto": " Eduardo Mendoza",
    "userName": "emendoza",
    "email": "emendoza@gmail.com"
}

### ALUMNOS --> DELETE (borrado lógico - solo lo puede hacer un administrador -)
DELETE http://localhost:3000/api/private/alumnos/delete/10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzcsInJvbGUiOiJhZG1pbiIsImV4cGlyYXRpb25fZGF0ZSI6MTY2ODYzMzQzNSwiaWF0IjoxNjY4NjE1NDM1fQ.uphy4WpcDC01sTI1EizOvAra8SB2WKVMdA1ew4FWAVc

##########################
### PRIVADO - USUARIOS ###
##########################
### ALUMNOS --> PUT (actualización del password del usuario - solo lo puede hacer él mismo -)
PUT http://localhost:3000/api/private/usuarios/update/password
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDAsInJvbGUiOiJhbHVtbm8iLCJleHBpcmF0aW9uX2RhdGUiOjE2Njg1ODQ2ODksImlhdCI6MTY2ODU2NjY4OX0.z4hRnKy40WM_x6-0N7-uTsa2FnYAKXN2vM0rzUbkwA4

{
    "password": "123456"
}

############################
### PRIVADO - PROFESORES ###
############################
### PROFESORES --> PUT (validación de un profesor - solo lo puede hacer un administrador -)
PUT http://localhost:3000/api/private/profesores/validate/10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzcsInJvbGUiOiJhZG1pbiIsImV4cGlyYXRpb25fZGF0ZSI6MTY2ODYzMzQzNSwiaWF0IjoxNjY4NjE1NDM1fQ.uphy4WpcDC01sTI1EizOvAra8SB2WKVMdA1ew4FWAVc

###############################
### PRIVADO - INSCRIPCIONES ###
###############################
### INSCRIPCIONES --> POST (solo lo puede hacer un alumno, el alumno cuyo id está en el token se inscribe con el profesor cuyo id está en el parámetro)
POST http://localhost:3000/api/private/inscripciones/signup/7
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDksInJvbGUiOiJhbHVtbm8iLCJleHBpcmF0aW9uX2RhdGUiOjE2Njg2Mzc1MzUsImlhdCI6MTY2ODYxOTUzNX0.7J7aIZxvxkXrI5tLqEXzaciUkZemFzlxvjC2QwSG8Bg

{    
}