### El API está levantada
http://localhost:3000/

### Documentación del API
http://localhost:3000/api-docs

#########################
### PUBLICO - LOGIN ###
#########################
### USUARIO --> POST (login de usuario)
POST http://localhost:3000/api/public/login
Content-Type: application/json

{
    "email": "mprieto@gmail.com",
    "password": "123456"
}

##########################
### PUBLICO - USUARIOS ###
##########################
### USUARIO --> POST (olvido de clave de usuario)
POST http://localhost:3000/api/public/usuarios/newpassword
Content-Type: application/json

{
    "email": "agutierrez@gmail.com"
}

#########################
### PUBLICO - ALUMNOS ###
#########################
### ALUMNOS --> POST (registro de un alumno)
POST http://localhost:3000/api/public/alumnos/register
Content-Type: application/json

{
    "nombreCompleto": "Antonio Gutierrez Márquez",
    "userName": "agutierrez",
    "email": "agutierrez@gmail.com",
    "password": "123456"
}

############################
### PUBLICO - PROFESORES ###
############################
### PROFESORES --> POST (registro de un profesor)
POST http://localhost:3000/api/public/profesores/register
Content-Type: application/json

{
    "nombreCompleto": "Martín Mayorga",
    "userName": "mmayorga",
    "email": "mmayorga@gmail.com",
    "password": "123456",
    "descripcion": "A tu disposición. Mejorarás", 
    "precioHora": 22, 
    "experiencia": 10,
    "latitud": 51.0754422,
    "longitud": 12.4878039, 
    "telefono": "555555555",
    "ramaId": 4
}

### PROFESORES --> POST (búsqueda de profesores) Aquí sin token
POST http://localhost:3000/api/public/profesores/getSearch
Content-Type: application/json

{
    "latitud": 51.0754421,
    "longitud": 12.4878035, 
    "maximaDistancia": 10000000,
    "orderByConditions": [
        {
            "column": "id",
            "order": "asc"
        }
    ]
}

### PROFESORES --> POST (búsqueda de profesores) Aquí con token
POST http://localhost:3000/api/public/profesores/getSearch
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjksInJvbGUiOiJhbHVtbm8iLCJleHBpcmF0aW9uX2RhdGUiOjE2Njk2ODgxNTYsImlhdCI6MTY2OTY3MDE1Nn0.Zn39AqLukdCuVTHqQVNoKESmB69xxymrHJYj-Gmo8Gs

{
    "latitud": 51.0754421,
    "longitud": 12.4878035, 
    "maximaDistancia": 100000000,
    "orderByConditions": [
        {
            "column": "id",
            "order": "asc"
        }
    ]
}

### PROFESORES/OPINIONES --> POST Recuperar opiniones del profesor
POST http://localhost:3000/api/public/profesores/opiniones/get
Content-Type: application/json

{
    "id": 7,
    "orderByConditions": [
        {
            "column": "puntuacion",
            "order": "asc"
        },
        {
            "column": "fechaPuntuacion",
            "order": "desc"
        }
    ]
}

#######################
### PUBLICO - RAMAS ###
#######################
### RAMAS --> GET (recuperamos todas)
http://localhost:3000/api/public/ramas/

### RAMAS --> GET (paginadas)
http://localhost:3000/api/public/ramas/?page=2&limit=2

#########################
### PRIVADO - ALUMNOS ###
#########################
### ALUMNOS --> PUT (actualización de los datos de un alumno que no sean la password - solo lo puede hacer él mismo -)
PUT http://localhost:3000/api/private/alumnos/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDcsInJvbGUiOiJhbHVtbm8iLCJleHBpcmF0aW9uX2RhdGUiOjE2Njg3MjQ3NjMsImlhdCI6MTY2ODcwNjc2M30.CIXXgwzo9dn0ygdwfPWFvC7oEKI6jt-vSPvVVBGl-1I

{
    "nombreCompleto": "Almudena Grandes Hernández",
    "userName": "agrandeshernandez",
    "email": "agrandes@gmail.com"
}

### ALUMNOS --> DELETE (borrado lógico - solo lo puede hacer un administrador -)
DELETE http://localhost:3000/api/private/alumnos/delete/10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzcsInJvbGUiOiJhZG1pbiIsImV4cGlyYXRpb25fZGF0ZSI6MTY2ODc4NTk2NywiaWF0IjoxNjY4NzY3OTY3fQ.0m8Zi9ui2Sc-Hb4biF5VdLjN-RGhEYkDakqF36griEY

### ALUMNOS --> PUT (deshace el borrado lógico - solo lo puede hacer un administrador -)
PUT http://localhost:3000/api/private/alumnos/undelete/10
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzcsInJvbGUiOiJhZG1pbiIsImV4cGlyYXRpb25fZGF0ZSI6MTY2ODc4NTk2NywiaWF0IjoxNjY4NzY3OTY3fQ.0m8Zi9ui2Sc-Hb4biF5VdLjN-RGhEYkDakqF36griEY

### ALUMNOS --> POST (recoger alumnos - devuelve todos si el token es de un administrador, o los no borrados de un profesor si el token tiene este rol -)
POST http://localhost:3000/api/private/alumnos/getSearch
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjgsInJvbGUiOiJwcm9mZXNvciIsImV4cGlyYXRpb25fZGF0ZSI6MTY2ODgwNTA5OSwiaWF0IjoxNjY4Nzg3MDk5fQ.zGYytmuWBO4zbK79pV9zkZNteJUzM31k_Zq61qtKaE8

###         --> Otro ejemplo
POST http://localhost:3000/api/private/alumnos/getSearch
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjgsInJvbGUiOiJwcm9mZXNvciIsImV4cGlyYXRpb25fZGF0ZSI6MTY2ODgwNTA5OSwiaWF0IjoxNjY4Nzg3MDk5fQ.zGYytmuWBO4zbK79pV9zkZNteJUzM31k_Zq61qtKaE8

{
    "searchConditions": [
        {
            "column": "id", 
            "operator": ">",
            "value": "11"
        }
    ]
}

###         --> Otro más
POST http://localhost:3000/api/private/alumnos/getSearch
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjgsInJvbGUiOiJwcm9mZXNvciIsImV4cGlyYXRpb25fZGF0ZSI6MTY2ODgwNTA5OSwiaWF0IjoxNjY4Nzg3MDk5fQ.zGYytmuWBO4zbK79pV9zkZNteJUzM31k_Zq61qtKaE8

{
    "searchConditions": [
        {
            "column": "borrado", 
            "operator": "=",
            "value": "0"
        },
        {
            "column": "email", 
            "operator": "like",
            "value": "*e*"
        }
    ]
}

###         --> El penúltimo
POST http://localhost:3000/api/private/alumnos/getSearch
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjgsInJvbGUiOiJwcm9mZXNvciIsImV4cGlyYXRpb25fZGF0ZSI6MTY2ODgwNTA5OSwiaWF0IjoxNjY4Nzg3MDk5fQ.zGYytmuWBO4zbK79pV9zkZNteJUzM31k_Zq61qtKaE8

{
    "searchConditions": [
        {
            "column": "borrado", 
            "operator": "=",
            "value": "0"
        },
        {
            "column": "email", 
            "operator": "like",
            "value": "*e*"
        }
    ],
    "orderByConditions": [
        {
            "column": "id",
            "order": "desc"
        }
    ]
}

###         --> El último
POST http://localhost:3000/api/private/alumnos/getSearch?page=2&limit=2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjgsInJvbGUiOiJwcm9mZXNvciIsImV4cGlyYXRpb25fZGF0ZSI6MTY2ODgwNTA5OSwiaWF0IjoxNjY4Nzg3MDk5fQ.zGYytmuWBO4zbK79pV9zkZNteJUzM31k_Zq61qtKaE8

{
    "searchConditions": [
        {
            "column": "borrado", 
            "operator": "=",
            "value": "0"
        },
        {
            "column": "email", 
            "operator": "like",
            "value": "*e*"
        }
    ],
    "orderByConditions": [
        {
            "column": "id",
            "order": "desc"
        }
    ]
}

##########################
### PRIVADO - USUARIOS ###
##########################
### ALUMNOS --> PUT (actualización del password del usuario - solo lo puede hacer él mismo -)
PUT http://localhost:3000/api/private/usuarios/update/password
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDAsInJvbGUiOiJhbHVtbm8iLCJleHBpcmF0aW9uX2RhdGUiOjE2Njg1ODQ2ODksImlhdCI6MTY2ODU2NjY4OX0.z4hRnKy40WM_x6-0N7-uTsa2FnYAKXN2vM0rzUbkwA4

{
    "password": "123456"
}

############################
### PRIVADO - PROFESORES ###
############################
### PROFESORES --> PUT (validación de un profesor - solo lo puede hacer un administrador -)
PUT http://localhost:3000/api/private/profesores/validate/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzcsInJvbGUiOiJhZG1pbiIsImV4cGlyYXRpb25fZGF0ZSI6MTY2OTY4Nzg3MSwiaWF0IjoxNjY5NjY5ODcxfQ.xXcLnQiQWn_7i-Kv67TD4qUpsFGopV4qJAqw8svO6Sw

### PROFESORES --> PUT (bloqueo de un profesor, vuelve a estar sin validar - solo lo puede hacer un administrador -)
PUT http://localhost:3000/api/private/profesores/lock/2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzcsInJvbGUiOiJhZG1pbiIsImV4cGlyYXRpb25fZGF0ZSI6MTY2OTY4Nzg3MSwiaWF0IjoxNjY5NjY5ODcxfQ.xXcLnQiQWn_7i-Kv67TD4qUpsFGopV4qJAqw8svO6Sw

### PROFESORES --> PUT (actualización de datos de un profesor - solo lo puede hacer él mismo -)
PUT http://localhost:3000/api/private/profesores/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODAsInJvbGUiOiJwcm9mZXNvciIsImV4cGlyYXRpb25fZGF0ZSI6MTY2ODcyNjQ4NiwiaWF0IjoxNjY4NzA4NDg2fQ.g8IdwbR3ugVx67lFV2l3QK2WclH-8kaAbv4uc9rMTgM

{
    "nombreCompleto": "Isaac Albéniz Fisher",
    "userName": "ialbenizfisher",
    "email": "ialbenizfisher@gmail.com",
    "password": "123456",
    "descripcion": "Análisis numérico a tu alcance. Fisher te lo garantiza.", 
    "precioHora": 22, 
    "experiencia": 10,
    "latitud": 51.0754469,
    "longitud": 12.4878069, 
    "telefono": "555555555F",
    "ramaId": 4
}

### PROFESORES --> POST (recoger profesores - devuelve todos si el token es de un administrador, o los validados de un alumno si el token tiene este rol -)
POST http://localhost:3000/api/private/profesores/getSearch
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjksInJvbGUiOiJhbHVtbm8iLCJleHBpcmF0aW9uX2RhdGUiOjE2Njk2ODgxNTYsImlhdCI6MTY2OTY3MDE1Nn0.Zn39AqLukdCuVTHqQVNoKESmB69xxymrHJYj-Gmo8Gs

###         --> Otro ejemplo
POST http://localhost:3000/api/private/profesores/getSearch
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzcsInJvbGUiOiJhZG1pbiIsImV4cGlyYXRpb25fZGF0ZSI6MTY2ODgyNTQ0NCwiaWF0IjoxNjY4ODA3NDQ0fQ.wbWmy5ltw97_s7s7OFIDpKmMNJdafgAo138a7SzoEJc

{
    "searchConditions": [
        {
            "column": "precioHora", 
            "operator": ">",
            "value": "5.50"
        }
    ]
}

###         --> Otro más
POST http://localhost:3000/api/private/profesores/getSearch
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzcsInJvbGUiOiJhZG1pbiIsImV4cGlyYXRpb25fZGF0ZSI6MTY2ODgyNTQ0NCwiaWF0IjoxNjY4ODA3NDQ0fQ.wbWmy5ltw97_s7s7OFIDpKmMNJdafgAo138a7SzoEJc

{
    "searchConditions": [
        {
            "column": "experiencia", 
            "operator": ">=",
            "value": "5"
        },
        {
            "column": "experiencia", 
            "operator": "<=",
            "value": "15"
        },
        {
            "column": "email", 
            "operator": "like",
            "value": "*e*"
        }
    ]
}

###         --> El penúltimo
POST http://localhost:3000/api/private/profesores/getSearch
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzcsInJvbGUiOiJhZG1pbiIsImV4cGlyYXRpb25fZGF0ZSI6MTY2ODgyNTQ0NCwiaWF0IjoxNjY4ODA3NDQ0fQ.wbWmy5ltw97_s7s7OFIDpKmMNJdafgAo138a7SzoEJc

{
    "searchConditions": [
        {
            "column": "experiencia", 
            "operator": ">=",
            "value": "5"
        },
        {
            "column": "experiencia", 
            "operator": "<=",
            "value": "15"
        },
        {
            "column": "email", 
            "operator": "like",
            "value": "*e*"
        },
        {
            "column": "validado", 
            "operator": "=",
            "value": "1"            
        }
    ],
    "orderByConditions": [
        {
            "column": "precioHora",
            "order": "desc"
        }
    ]
}

###         --> El último
POST http://localhost:3000/api/private/profesores/getSearch?page=1&limit=2
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDcsInJvbGUiOiJhbHVtbm8iLCJleHBpcmF0aW9uX2RhdGUiOjE2Njg4MjY0MTYsImlhdCI6MTY2ODgwODQxNn0.jXsGj_1psjMtHSi18YX4rplu40LhmA0laimMouemCE0

{
    "searchConditions": [
        {
            "column": "experiencia", 
            "operator": ">=",
            "value": "5"
        },
        {
            "column": "experiencia", 
            "operator": "<=",
            "value": "15"
        },
        {
            "column": "email", 
            "operator": "like",
            "value": "*e*"
        }
    ],
    "orderByConditions": [
        {
            "column": "precioHora",
            "order": "desc"
        }
    ]
}

###############################
### PRIVADO - INSCRIPCIONES ###
###############################
### INSCRIPCIONES --> POST (solo lo puede hacer un alumno, el alumno cuyo id está en el token se inscribe con el profesor cuyo id está en el parámetro)
POST http://localhost:3000/api/private/inscripciones/signup/7
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ODcsInJvbGUiOiJhbHVtbm8iLCJleHBpcmF0aW9uX2RhdGUiOjE2Njg4OTkwODQsImlhdCI6MTY2ODg4MTA4NH0.cHBIKHbI5F9loOjb8zKRBHyeHKcjfFbYnpGO_-m1EZ0

{    
}

### ACEPTACIÓN INSCRIPCIÓN --> PUT (solo lo puede hacer un profesor, el profesor cuyo id está en el token se acepta la inscripción cuyo id está en el parámetro)
PUT http://localhost:3000/api/private/inscripciones/accept/6
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NzMsInJvbGUiOiJwcm9mZXNvciIsImV4cGlyYXRpb25fZGF0ZSI6MTY2ODY0MTc2MSwiaWF0IjoxNjY4NjIzNzYxfQ.u63HAxcSFN6gfBKlWeDwAGVdxN7mc2-7y6AwikCIXV8

{    
}

### OPINION INSCRIPCIÓN --> PUT (solo lo puede hacer un alumno, el alumno cuyo id está en el token envía una opinón sobre la inscripción cuyo id está en el cuerpo de la petición)
PUT http://localhost:3000/api/private/inscripciones/opinion
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDcsInJvbGUiOiJhbHVtbm8iLCJleHBpcmF0aW9uX2RhdGUiOjE2Njg2NTQ1MjYsImlhdCI6MTY2ODYzNjUyNn0.jopqxBdXxaaDypeVkra-EmQfLWG6O8KA1NXOshPOy0A

{
    "id": 2,
    "puntuacion": 4,
    "comentario": "Muy satisfecha, contenta con el resultado."
}

### INSCRIPCIONES DE ALUMNO --> POST (Devuelve las inscripciones del alumno cuyo id va en el token. Permite parámetros de búsqueda/ordenación/paginación)
POST http://localhost:3000/api/private/inscripciones/alumnos/getSearch
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDcsInJvbGUiOiJhbHVtbm8iLCJleHBpcmF0aW9uX2RhdGUiOjE2Njg5MTQ5NDIsImlhdCI6MTY2ODg5Njk0Mn0.7WRywMRtWaBBu0PvZN6j5fbr2ERceFDrcRpESGQD7IE

###         --> Otro ejemplo
POST http://localhost:3000/api/private/inscripciones/alumnos/getSearch
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NDcsInJvbGUiOiJhbHVtbm8iLCJleHBpcmF0aW9uX2RhdGUiOjE2Njg5MTQ5NDIsImlhdCI6MTY2ODg5Njk0Mn0.7WRywMRtWaBBu0PvZN6j5fbr2ERceFDrcRpESGQD7IE

{
    "orderByConditions": [
        {
            "column": "nombreCompleto", 
            "order": "asc"
        }
    ]
}

### INSCRIPCIONES A PROFESOR --> POST (Devuelve las inscripciones al proefesor cuyo id va en el token. Permite parámetros de búsqueda/ordenación/paginación)
POST http://localhost:3000/api/private/inscripciones/profesores/getSearch
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjgsInJvbGUiOiJwcm9mZXNvciIsImV4cGlyYXRpb25fZGF0ZSI6MTY2ODkxNDI5NCwiaWF0IjoxNjY4ODk2Mjk0fQ.9cNDK26ZiVN1-rayeS_rWI0jHtVvsb7X3HBMxqPWib4

###         --> Otro ejemplo
POST http://localhost:3000/api/private/inscripciones/profesores/getSearch
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NjgsInJvbGUiOiJwcm9mZXNvciIsImV4cGlyYXRpb25fZGF0ZSI6MTY2ODkxNDI5NCwiaWF0IjoxNjY4ODk2Mjk0fQ.9cNDK26ZiVN1-rayeS_rWI0jHtVvsb7X3HBMxqPWib4

{
    "orderByConditions": [
        {
            "column": "nombreCompleto", 
            "order": "asc"
        }
    ]
}

#######################
### PRIVADO - RAMAS ###
#######################
### Ramas --> POST Da de alta una nueva rama (solo lo puede hacer un administrador)
POST http://localhost:3000/api/private/ramas/
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzcsInJvbGUiOiJhZG1pbiIsImV4cGlyYXRpb25fZGF0ZSI6MTY2OTA4Nzg4NywiaWF0IjoxNjY5MDY5ODg3fQ.KfrVb5yjb8ssM2PJ66xU5OvryCeAxGKpEPDAz2xCwX8

{
    "nombre": "Borrable"
}

### Ramas --> PUT Modificación de una rama (solo lo puede hacer un administrador)
PUT http://localhost:3000/api/private/ramas/19
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzcsInJvbGUiOiJhZG1pbiIsImV4cGlyYXRpb25fZGF0ZSI6MTY2OTA4Nzg4NywiaWF0IjoxNjY5MDY5ODg3fQ.KfrVb5yjb8ssM2PJ66xU5OvryCeAxGKpEPDAz2xCwX8

{
    "nombre": "Modificado"
}

### Ramas --> Borra una rama (solo lo puede hacer un administrador y si no está ligada a un profesor)
DELETE http://localhost:3000/api/private/ramas/18
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzcsInJvbGUiOiJhZG1pbiIsImV4cGlyYXRpb25fZGF0ZSI6MTY2OTA4Nzg4NywiaWF0IjoxNjY5MDY5ODg3fQ.KfrVb5yjb8ssM2PJ66xU5OvryCeAxGKpEPDAz2xCwX8
